#include <stdio.h>
#include <sql.h>
#include <sqlext.h>

char *
sqlinfo_name (int infotype)
{
  typedef struct
    {
      int type;
      char *name;
    } SQLINFONAMES;
   SQLINFONAMES sql_infotype_list [] = {
    {SQL_DRIVER_HDBC,			"SQL_DRIVER_HDBC"},
    {SQL_DRIVER_HENV,			"SQL_DRIVER_HENV"},
    {SQL_DRIVER_HSTMT,			"SQL_DRIVER_HSTMT"},
    {SQL_DRIVER_NAME,			"SQL_DRIVER_NAME"},
    {SQL_DRIVER_VER,			"SQL_DRIVER_VER"},
    {SQL_ODBC_API_CONFORMANCE,		"SQL_ODBC_API_CONFORMANCE"},
    {SQL_ODBC_VER,			"SQL_ODBC_VER"},

    {SQL_MAX_DRIVER_CONNECTIONS,	"SQL_MAX_DRIVER_CONNECTIONS"},
    {SQL_MAXIMUM_DRIVER_CONNECTIONS,	"SQL_MAXIMUM_DRIVER_CONNECTIONS"},
    {SQL_MAX_CONCURRENT_ACTIVITIES,	"SQL_MAX_CONCURRENT_ACTIVITIES"},
    {SQL_MAXIMUM_CONCURRENT_ACTIVITIES,	"SQL_MAXIMUM_CONCURRENT_ACTIVITIES"},
    {SQL_DATA_SOURCE_NAME,		"SQL_DATA_SOURCE_NAME"},
    {SQL_FETCH_DIRECTION,		"SQL_FETCH_DIRECTION"},
    {SQL_SERVER_NAME,			"SQL_SERVER_NAME"},
    {SQL_SEARCH_PATTERN_ESCAPE,		"SQL_SEARCH_PATTERN_ESCAPE"},

    {SQL_DBMS_NAME,			"SQL_DBMS_NAME"},
    {SQL_DBMS_VER,			"SQL_DBMS_VER"},
    {SQL_ACCESSIBLE_TABLES,		"SQL_ACCESSIBLE_TABLES"},
    {SQL_ACCESSIBLE_PROCEDURES,		"SQL_ACCESSIBLE_PROCEDURES"},
    {SQL_CURSOR_COMMIT_BEHAVIOR,	"SQL_CURSOR_COMMIT_BEHAVIOR"},
    {SQL_DATA_SOURCE_READ_ONLY,		"SQL_DATA_SOURCE_READ_ONLY"},
    {SQL_DEFAULT_TXN_ISOLATION,		"SQL_DEFAULT_TXN_ISOLATION"},
    {SQL_IDENTIFIER_CASE,		"SQL_IDENTIFIER_CASE"},
    {SQL_IDENTIFIER_QUOTE_CHAR,		"SQL_IDENTIFIER_QUOTE_CHAR"},
    {SQL_MAX_COLUMN_NAME_LEN,		"SQL_MAX_COLUMN_NAME_LEN"},
    {SQL_MAXIMUM_COLUMN_NAME_LENGTH,	"SQL_MAXIMUM_COLUMN_NAME_LENGTH"},
    {SQL_MAX_CURSOR_NAME_LEN,		"SQL_MAX_CURSOR_NAME_LEN"},
    {SQL_MAXIMUM_CURSOR_NAME_LENGTH,	"SQL_MAXIMUM_CURSOR_NAME_LENGTH"},
    {SQL_MAX_SCHEMA_NAME_LEN,		"SQL_MAX_SCHEMA_NAME_LEN"},
    {SQL_MAXIMUM_SCHEMA_NAME_LENGTH,	"SQL_MAXIMUM_SCHEMA_NAME_LENGTH"},
    {SQL_MAX_CATALOG_NAME_LEN,		"SQL_MAX_CATALOG_NAME_LEN"},
    {SQL_MAX_TABLE_NAME_LEN,		"SQL_MAX_TABLE_NAME_LEN"},
    {SQL_SCROLL_CONCURRENCY,		"SQL_SCROLL_CONCURRENCY"},
    {SQL_TXN_CAPABLE,			"SQL_TXN_CAPABLE"},
    {SQL_USER_NAME,			"SQL_USER_NAME"},
    {SQL_TXN_ISOLATION_OPTION,		"SQL_TXN_ISOLATION_OPTION"},
    {SQL_INTEGRITY,			"SQL_INTEGRITY"},
    {SQL_GETDATA_EXTENSIONS,		"SQL_GETDATA_EXTENSIONS"},
    {SQL_NULL_COLLATION,		"SQL_NULL_COLLATION"},
    {SQL_ALTER_TABLE,			"SQL_ALTER_TABLE"},
    {SQL_ORDER_BY_COLUMNS_IN_SELECT,	"SQL_ORDER_BY_COLUMNS_IN_SELECT"},
    {SQL_SPECIAL_CHARACTERS,		"SQL_SPECIAL_CHARACTERS"},
    {SQL_MAX_COLUMNS_IN_GROUP_BY,	"SQL_MAX_COLUMNS_IN_GROUP_BY"},
    {SQL_MAX_COLUMNS_IN_INDEX,		"SQL_MAX_COLUMNS_IN_INDEX"},
    {SQL_MAX_COLUMNS_IN_ORDER_BY,	"SQL_MAX_COLUMNS_IN_ORDER_BY"},
    {SQL_MAX_COLUMNS_IN_SELECT,		"SQL_MAX_COLUMNS_IN_SELECT"},
    {SQL_SPECIAL_CHARACTERS,		"SQL_SPECIAL_CHARACTERS"},
    {SQL_MAX_COLUMNS_IN_GROUP_BY,	"SQL_MAX_COLUMNS_IN_GROUP_BY"},
    {SQL_MAX_COLUMNS_IN_INDEX,		"SQL_MAX_COLUMNS_IN_INDEX"},
    {SQL_MAX_COLUMNS_IN_ORDER_BY,	"SQL_MAX_COLUMNS_IN_ORDER_BY"},
    {SQL_MAX_COLUMNS_IN_SELECT,		"SQL_MAX_COLUMNS_IN_SELECT"},
    {SQL_MAX_COLUMNS_IN_TABLE,		"SQL_MAX_COLUMNS_IN_TABLE"},
    {SQL_MAX_INDEX_SIZE,		"SQL_MAX_INDEX_SIZE"},
    {SQL_MAX_ROW_SIZE,			"SQL_MAX_ROW_SIZE"},
    {SQL_MAX_STATEMENT_LEN,		"SQL_MAX_STATEMENT_LEN"},
    {SQL_MAX_TABLES_IN_SELECT,		"SQL_MAX_TABLES_IN_SELECT"},
    {SQL_MAX_USER_NAME_LEN,		"SQL_MAX_USER_NAME_LEN"},
    // ODBCVER >= 0x0300
    {SQL_OJ_CAPABILITIES,		"SQL_OJ_CAPABILITIES"},
    {SQL_XOPEN_CLI_YEAR,		"SQL_XOPEN_CLI_YEAR"},
    {SQL_CURSOR_SENSITIVITY,		"SQL_CURSOR_SENSITIVITY"},
    {SQL_DESCRIBE_PARAMETER,		"SQL_DESCRIBE_PARAMETER"},
    {SQL_CATALOG_NAME,			"SQL_CATALOG_NAME"},
    {SQL_COLLATION_SEQ,			"SQL_COLLATION_SEQ"},
    {SQL_MAX_IDENTIFIER_LEN,		"SQL_MAX_IDENTIFIER_LEN"},
    {SQL_QUOTED_IDENTIFIER_CASE,	"SQL_QUOTED_IDENTIFIER_CASE"},
    {SQL_OWNER_USAGE,			"SQL_OWNER_USAGE"},

    {SQL_MAX_PROCEDURE_NAME_LEN,	"SQL_MAX_PROCEDURE_NAME_LEN"},
    {SQL_COLUMN_ALIAS,			"SQL_COLUMN_ALIAS"},
    {SQL_CURSOR_ROLLBACK_BEHAVIOR,	"SQL_CURSOR_ROLLBACK_BEHAVIOR"},
    {SQL_CURSOR_ROLLBACK_BEHAVIOR,	"SQL_CURSOR_ROLLBACK_BEHAVIOR"},
    {-1,  "UNKNOWN_SQL_INFO_TYPE"}
  };
  char *unknown_id = "UNKNOWN_SQL_INFO_TYPE";
  int len = sizeof (sql_infotype_list) / sizeof (SQLINFONAMES);
  int i;

  for (i = 0; i < len; i++)
    {
      if (infotype == sql_infotype_list[i].type)
        {
          break;
        }
    }

  return i == len ? unknown_id : sql_infotype_list[i].name;
}


char *
sqltype_name (SQLSMALLINT sqltype)
{
  typedef struct
    {
      int sqltype;
      char *name;
    } SQLTYPENAME;
   SQLTYPENAME sql_typename_list [] = {
    {SQL_C_WCHAR,	"SQL_C_WCHAR"},
    {SQL_C_CHAR,	"SQL_C_CHAR"},
    {SQL_C_SSHORT,	"SQL_C_SSHORT"},
    {SQL_C_SLONG,	"SQL_C_SLONG"},
    {SQL_C_CHAR,	"SQL_C_CHAR"},
    {SQL_C_FLOAT,	"SQL_C_FLOAT"},
    {SQL_C_DATE,	"SQL_C_DATE"},
    {SQL_C_TIME,	"SQL_C_TIME"},
    {SQL_C_TIMESTAMP,	"SQL_C_TIMESTAMP"},
  };

  static char buf [128] = "";
  int len = sizeof (sql_typename_list) / sizeof (SQLTYPENAME);
  int i;

  for (i = 0; i < len; i++)
    {
      if (sqltype == sql_typename_list[i].sqltype)
        {
          break;
        }
    }

  if (i == len)
    {
      snprintf (buf, sizeof (buf), "%d", sqltype);
    }
  
  return (i == len) ? buf : sql_typename_list[i].name;
}
